name: "errático"
description: "a blog by some dude."

author: "Artur Upton Renault"

url: "errati.co"
baseurl: ""
encoding: utf-8

relative_permalinks: true
markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: errati.co
ga_tracking_id:
