name: "errático"
description: "a blog by some dude."

author: "Artur Upton Renault"

url: "errati.co"
baseurl: ""
encoding: utf-8

email: arturenault@gmail.com
github: http://www.github.com/arturenault
facebook: http://www.facebook.com/arturenault
twitter: http://www.twitter.com/arturenault
instagram: http://www.instagram.com/arturenault
linkedin: https://www.linkedin.com/pub/artur-renault/60/66/665

relative_permalinks: true
markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: errati.co
ga_tracking_id: UA-52878304-1