name: "errático"
description: "a blog."

author: "Artur Upton Renault"

url: "errati.co"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: errati.co
ga_tracking_id:
